### ISSUE TITLE
Add possibility to provide a list of excluded files or variables

### ISSUE THREAD

**Issue by bogdannbv** [backdevs/laravel-dotenv-sniffer#112]
This can (should?) be done similar to what `phpunit` or `phpcs` do with their configuration files (`phpcs.xml` and `phpunit.xml`).

We can have a `desniff.yml` file that can look something like this:

```yml
excluded_files:
    - ./config/view.php
    - ./config/queue.php

excluded_vars:
    # config/app.php
    - ASSET_URL

   # config/view.php
    - VIEW_COMPILED_PATH

   # config/broadcasting.php
    - PUSHER_APP_KEY
    - PUSHER_APP_SECRET
    - PUSHER_APP_ID
    - PUSHER_APP_CLUSTER
```
